version: '3.9'

services:
  neo4j:
    image: neo4j:3.5
    container_name: clusterdb
    restart: unless-stopped
    platform: linux/amd64
    ports:
      - 7474:7474
      - 7687:7687
    volumes:
      - ./database/conf:/conf
      - ./database/data:/data
      - ./database/import:/import
      - ./database/logs:/logs
      - ./database/plugins:/plugins
    env_file:
      - .env
networks:
  default:
      external:
        name: trinit_network